---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app1
  namespace: dev
spec:
  rules:
  - host: www.wis.com
    http:
      paths:
      - backend:
          serviceName: app1
          servicePort: 8080
  - host: static.wis.com
    http:
      paths:
      - backend:
          serviceName: static
          servicePort: 80